#@TYPE: Machine
#@NAME: intel-x86-64-tqmx86

#@DESCRIPTION: Machine configuration for TQ modules with 64 bit Intel CPUs

# Disable hddimg - intel-corei7-64 adds wic type
IMAGE_FSTYPES ?= ""

# We want linux-yocto, not linux-intel
PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_PROVIDER_virtual/kernel:poky-tiny ?= "linux-yocto"

# intel-x86-64-tqmx86 covers both i7-compatbiles and various Atom variants.
# intel-corei7-64.conf provides a good set of defaults that are useful for
# all 64 bit Intel CPUs, not only i7.
MACHINEOVERRIDES =. "tqmx86:"
require conf/machine/intel-corei7-64.conf

APPEND += "acpi_enforce_resources=lax"

SERIAL_CONSOLES = "115200;ttyS0"
