#@TYPE: Machine
#@NAME: intel-x86-64-tqmx86

#@DESCRIPTION: Machine configuration for TQ modules with 64 bit Intel CPUs

# We want linux-yocto, not linux-intel
PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_PROVIDER_virtual/kernel:poky-tiny ?= "linux-yocto"

PREFERRED_VERSION_linux-yocto = "6.12.%"
PREFERRED_VERSION_linux-yocto-rt = "6.12.%"

# intel-x86-64-tqmx86 covers both i7-compatbiles and various Atom variants.
# intel-corei7-64.conf provides a good set of defaults that are useful for
# all 64 bit Intel CPUs, not only i7.
MACHINEOVERRIDES =. "tqmx86:"
require conf/machine/intel-corei7-64.conf

# We default to tar.zst for NFS, wic.zst for SD/eMMC
#
# It is set unconditionally and should be included after SoC includes to override differing
# settings from vendor layers.
TQ_IMAGE_COMPRESSION ?= ".zst"
IMAGE_FSTYPES = "tar${TQ_IMAGE_COMPRESSION} wic${TQ_IMAGE_COMPRESSION} wic.bmap"

APPEND += "acpi_enforce_resources=lax"

SERIAL_CONSOLES = "115200;ttyS0"
