require conf/distro/pretzel.conf

DISTRO = "pretzel-rt"
DISTROOVERRIDES = "pretzel-rt:pretzel"
DISTRO_NAME = "Pretzel-RT (TQ-Systems Distribution for TQMx86 BSP)"

PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-rt"
