require conf/distro/poky.conf

DISTRO = "pretzel"
DISTROOVERRIDES = "pretzel"
DISTRO_NAME = "Pretzel (TQ-Systems Distribution for TQMx86 BSP)"

DISTRO_FEATURES += "efi pam systemd usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
ROOT_HOME ?= "/root"

PACKAGECONFIG:pn-alsa-utils:append = " bat"

DISTRO_EXTRA_RRECOMMENDS += " \
    alsa-utils \
    alsa-utils-alsabat \
    can-utils \
    cpufrequtils \
    evtest \
    fb-test \
    findutils \
    i2c-tools \
    libgpiod-tools \
    lmsensors-sensors \
    openssh \
    ptn3460-edid-tool \
    usbutils \
    util-linux \
"
